sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QXdN/pq3R/CgNuJt8Y8oS+Dzr1fiJr1GoMpWmYSaD3Nor1soV4mQsTD/g7xpDA7LirvXDHBFmV3YFWkFSnSIrvu0docRaHRWirN4Zg83reGjcIK9NMXkkZebN/xPeAQOoESK/NsmuQHnBw68gfaJn//YDVUU5lkIzmRbyrYh/cfWt6JblANI+Z5RWwJw79hfta6IsfFmNOChvqkg9oAnEUJ/duGAN6J+Ak5xyFRxRSAOXFkKo5X3o3t6WWQlvR/nyA+T+AT5R80QEetU6Bi1NaNCLIdmvU7HJQYqVUG79m1uH+mte0Ekm1Xk7q/sx11bH5qsFNnuqhs3pxAbM5RAuANRIduB9MKIvWBkLkRpUxMmCQ9WVHvaTW0jW/B5boetVtZvwSAX2KrPaOBBVJgAWXbVw9bpLAmP0LvJc1m85veHaAGjWtvwpFLFM0O9+PU1VANZjbqToxSQBnUzv6aOJkdHjkJq7ztnvjCKf0XrN8/vTyDxKBEKM+q7mtyazK8cR/koarPd8fIZnQPQ1iEicB99T8TZpXR2O4GdBJiU9RXnA6YeQOm81uU7YNQQt7oGJR35Kxh+4H/SrAC9uDe8tT7emrRabzHj7PZvQ+eO+6W0eJ5w2YPwE6a9jFV6UMIR8ypGnoSwyYhD12dYfy+VYB0UJUIaq8kFO+mAfLb8TUs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Elinor-Wyllys-Or-The-Young-Folk-of-Longbridge-A-Tale-Volume-2_1928
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy